name: testPR
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 7.0.x 
    - name: Execute Cake
      shell : bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        dotnet tool restore
        dotnet cake --target=Test